name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: read

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

  build:
    name: Build
    runs-on: ubuntu-22.04
    needs: setup
    steps:
      - run: go build -v ./...

  test:
    name: Test
    runs-on: ubuntu-22.04
    needs: setup
    steps:
      - run: go test -v ./...
